<a href="https://colab.research.google.com/github/thomaslu678/Praxis-Lab-25-26/blob/main/clean/18_Similarity_Score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [1]:
pip install kgcPy

Collecting kgcPy
  Downloading kgcpy-1.1.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from kgcPy) (11.3.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from kgcPy) (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->kgcPy) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->kgcPy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->kgcPy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->kgcPy) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->kgcPy) (1.17.0)
Downloading kgcpy-1.1.8-py3-none-any.whl (834 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 834.6/834.6 kB 7.4 MB/s eta 0:00:00
Installing collected packages: kgcPy
Successfully installed kgcPy-1.1.8

In [50]:
import json

# Get feature weight vector for climate

In [2]:
import io
import pandas as pd
import numpy as np
from scipy.optimize import minimize

In [12]:
raw_csvs = []
user_weights = [0.5, 0.5]

In [5]:
np.sum(user_weights)

np.float64(1.0)

In [4]:
user_1 = pd.read_csv(io.StringIO('''
,1,3,5
,,2,6
,,,2
,,,
'''), header=None)

In [6]:
user_2 = pd.read_csv(io.StringIO('''
,1/7,1/6,5
,,3,6
,,,5
,,,
'''), header=None)

In [7]:
# 2. Helper function to turn fraction strings into actual floats
def parse_fraction(val):
    if pd.isna(val) or str(val).strip() == "":
        return np.nan
    val = str(val).strip()
    if "/" in val:
        num, denom = val.split("/")
        return float(num) / float(denom)
    return float(val)

def get_numeric_df(sheets_csv):
    df_numeric = sheets_csv.map(parse_fraction)

    # 3. Populate the main diagonal with 1s
    np.fill_diagonal(df_numeric.values, 1.0)

    # 4. Fill the lower triangle with the reciprocals of the upper triangle
    # We iterate only through the lower triangle coordinates
    for i in range(len(df_numeric)):
        for j in range(i):
            df_numeric.iloc[i, j] = 1.0 / df_numeric.iloc[j, i]

    return df_numeric

In [8]:
def get_real_principal_eigenvector(df_numeric):
    # Compute eigenvalues and right eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(df_numeric)

    # Find the index of the largest eigenvalue
    max_index = np.argmax(eigenvalues)

    # Extract the principal eigenvector (stored as a column)
    principal_eigenvector = eigenvectors[:, max_index]

    return principal_eigenvector.real

In [13]:
raw_csvs.append(get_numeric_df(user_1))
raw_csvs.append(get_numeric_df(user_2))

In [14]:
raw_csvs

[          0         1    2    3
 0  1.000000  1.000000  3.0  5.0
 1  1.000000  1.000000  2.0  6.0
 2  0.333333  0.500000  1.0  2.0
 3  0.200000  0.166667  0.5  1.0,
      0         1         2    3
 0  1.0  0.142857  0.166667  5.0
 1  7.0  1.000000  3.000000  6.0
 2  6.0  0.333333  1.000000  5.0
 3  0.2  0.166667  0.200000  1.0]

In [15]:
raw_weights = []

In [16]:
for csv in raw_csvs:
    weight = get_real_principal_eigenvector(get_numeric_df(csv))
    sum = np.sum(weight)
    normalized = weight / sum
    raw_weights.append(normalized)

In [17]:
raw_weights

[array([0.39694211, 0.37670033, 0.15391312, 0.07244444]),
 array([0.1053004 , 0.54633237, 0.29962718, 0.04874005])]

In [18]:
average_climate_weights = (raw_weights[0] + raw_weights[1]) / 2

In [19]:
average_climate_weights

array([0.25112125, 0.46151635, 0.22677015, 0.06059225])

## edbam (only necessary with non-equal user weights

In [ ]:
def edbam(individual_weights, stakeholder_weights):
    """
    Calculate the Euclidean Distance-Based Aggregation Method (EDBAM)
    group weight vector.

    Parameters
    ----------
    individual_weights : np.ndarray
        Array of shape (m, n), where each row is one stakeholder's
        normalized principal eigenvector.

    stakeholder_weights : np.ndarray
        Array of shape (m,), containing the stakeholder weights.
        Must sum to 1.

    Returns
    -------
    group_weights : np.ndarray
        EDBAM aggregated weight vector of shape (n,).
        Sums to 1.
    """

    individual_weights = np.asarray(individual_weights, dtype=float)
    stakeholder_weights = np.asarray(stakeholder_weights, dtype=float)

    # Basic validation
    if individual_weights.ndim != 2:
        raise ValueError("individual_weights must be a 2D array.")

    m, n = individual_weights.shape

    if stakeholder_weights.shape != (m,):
        raise ValueError(
            "stakeholder_weights must have one value per stakeholder."
        )

    if np.any(individual_weights < 0):
        raise ValueError("Individual weight vectors must be non-negative.")

    if np.any(stakeholder_weights < 0):
        raise ValueError("Stakeholder weights must be non-negative.")

    if not np.isclose(stakeholder_weights.sum(), 1.0):
        raise ValueError("Stakeholder weights must sum to 1.")

    if not np.allclose(individual_weights.sum(axis=1), 1.0):
        raise ValueError(
            "Each individual weight vector must sum to 1."
        )

    # Objective function:
    #
    # f(x) = sum_k a_k * ||w^(k) - x||_2
    #
    def objective(x):
        distances = np.linalg.norm(individual_weights - x, axis=1)
        return np.dot(stakeholder_weights, distances)

    # Initial guess: weighted arithmetic mean.
    # This is a convenient starting point, NOT the EDBAM solution.
    x0 = np.average(
        individual_weights,
        axis=0,
        weights=stakeholder_weights
    )

    # Constrain x to be a valid weight vector:
    # x_i >= 0
    # sum(x_i) = 1
    constraints = {
        "type": "eq",
        "fun": lambda x: np.sum(x) - 1.0
    }

    bounds = [(0.0, 1.0)] * n

    result = minimize(
        objective,
        x0,
        method="SLSQP",
        bounds=bounds,
        constraints=constraints,
        options={
            "ftol": 1e-12,
            "maxiter": 1000
        }
    )

    if not result.success:
        raise RuntimeError(
            f"EDBAM optimization failed: {result.message}"
        )

    # Final normalization for numerical precision
    group_weights = result.x / result.x.sum()

    return group_weights

In [ ]:
group_weights = edbam(
    raw_weights,
    user_weights
)

print(group_weights)
print(group_weights.sum())

[0.0376873  0.26562517 0.15387367 0.06659161 0.47622226]
1.0000000000000002

In [ ]:
import io
import pandas as pd
import numpy as np
from scipy.optimize import minimize

In [ ]:
raw_csvs = []
user_weights = [0.5, 0.5]

In [ ]:
np.sum(user_weights)

np.float64(1.0)

In [ ]:
user_1 = pd.read_csv(io.StringIO('''
,1,3,5
,,2,6
,,,2
,,,
'''), header=None)

In [ ]:
user_2 = pd.read_csv(io.StringIO('''
,1/7,1/6,5
,,3,6
,,,5
,,,
'''), header=None)

In [ ]:
# 2. Helper function to turn fraction strings into actual floats
def parse_fraction(val):
    if pd.isna(val) or str(val).strip() == "":
        return np.nan
    val = str(val).strip()
    if "/" in val:
        num, denom = val.split("/")
        return float(num) / float(denom)
    return float(val)

def get_numeric_df(sheets_csv):
    df_numeric = sheets_csv.map(parse_fraction)

    # 3. Populate the main diagonal with 1s
    np.fill_diagonal(df_numeric.values, 1.0)

    # 4. Fill the lower triangle with the reciprocals of the upper triangle
    # We iterate only through the lower triangle coordinates
    for i in range(len(df_numeric)):
        for j in range(i):
            df_numeric.iloc[i, j] = 1.0 / df_numeric.iloc[j, i]

    return df_numeric

In [ ]:
def get_real_principal_eigenvector(df_numeric):
    # Compute eigenvalues and right eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(df_numeric)

    # Find the index of the largest eigenvalue
    max_index = np.argmax(eigenvalues)

    # Extract the principal eigenvector (stored as a column)
    principal_eigenvector = eigenvectors[:, max_index]

    return principal_eigenvector.real

In [ ]:
raw_csvs.append(get_numeric_df(user_1))
raw_csvs.append(get_numeric_df(user_2))

In [ ]:
raw_csvs

[          0         1    2    3
 0  1.000000  1.000000  3.0  5.0
 1  1.000000  1.000000  2.0  6.0
 2  0.333333  0.500000  1.0  2.0
 3  0.200000  0.166667  0.5  1.0,
      0         1         2    3
 0  1.0  0.142857  0.166667  5.0
 1  7.0  1.000000  3.000000  6.0
 2  6.0  0.333333  1.000000  5.0
 3  0.2  0.166667  0.200000  1.0]

In [ ]:
raw_weights = []

In [ ]:
for csv in raw_csvs:
    weight = get_real_principal_eigenvector(get_numeric_df(csv))
    sum = np.sum(weight)
    normalized = weight / sum
    raw_weights.append(normalized)

In [ ]:
raw_weights

[array([0.39694211, 0.37670033, 0.15391312, 0.07244444]),
 array([0.1053004 , 0.54633237, 0.29962718, 0.04874005])]

In [ ]:
average_climate_weights = (raw_weights[0] + raw_weights[1]) / 2

In [ ]:
average_climate_weights

array([0.25112125, 0.46151635, 0.22677015, 0.06059225])

# Get feature weight vector for case

In [22]:
import io
import pandas as pd
import numpy as np
from scipy.optimize import minimize

In [23]:
raw_csvs = []
user_weights = [0.5, 0.5]

In [24]:
np.sum(user_weights)

np.float64(1.0)

In [25]:
user_1 = pd.read_csv(io.StringIO('''
,1/6,1/5,1/3,1/8
,,1/2,2,1/5
,,,2,1/2
,,,,1/6
,,,,
'''), header=None)

In [26]:
user_2 = pd.read_csv(io.StringIO('''
,1/7,1/6,1/5,1/7
,,1,6,2
,,,6,2
,,,,1/6
,,,,
'''), header=None)

In [27]:
raw_csvs.append(get_numeric_df(user_1))
raw_csvs.append(get_numeric_df(user_2))

In [28]:
raw_csvs

[     0         1    2         3         4
 0  1.0  0.166667  0.2  0.333333  0.125000
 1  6.0  1.000000  0.5  2.000000  0.200000
 2  5.0  2.000000  1.0  2.000000  0.500000
 3  3.0  0.500000  0.5  1.000000  0.166667
 4  8.0  5.000000  2.0  6.000000  1.000000,
      0         1         2    3         4
 0  1.0  0.142857  0.166667  0.2  0.142857
 1  7.0  1.000000  1.000000  6.0  2.000000
 2  6.0  1.000000  1.000000  6.0  2.000000
 3  5.0  0.166667  0.166667  1.0  0.166667
 4  7.0  0.500000  0.500000  6.0  1.000000]

In [29]:
raw_weights = []

In [30]:
for csv in raw_csvs:
    weight = get_real_principal_eigenvector(get_numeric_df(csv))
    sum = np.sum(weight)
    normalized = weight / sum
    raw_weights.append(normalized)

In [31]:
raw_weights

[array([0.03892579, 0.15076397, 0.22263472, 0.09252666, 0.49514886]),
 array([0.0342157 , 0.33448927, 0.32813251, 0.07298866, 0.23017387])]

In [32]:
average_case_weights = (raw_weights[0] + raw_weights[1]) / 2

In [33]:
average_case_weights

array([0.03657074, 0.24262662, 0.27538361, 0.08275766, 0.36266136])

# Get all similarity scores

In [72]:
data = pd.read_csv(io.StringIO('''
ID,xmin,ymin,Duration,Pop. Start
0,,,7,"307,006"
1,-84.37347649,33.75400957,3,"483,450"
2,,,2,"472,330"
3,-87.7126679,41.91046952,2,"2,718,782"
4,-99.20962876,19.43531808,1,"8,918,653"
5,-99.11203944,19.43137642,3,"8,920,000"
6,-111.9105146,40.74596957,6,"200,546"
7,127.0737116,37.61597727,9,"2,660,000"
8,126.9129689,37.5548156,6,"2,660,000"
9,-74.00025074,40.7496983,8,"8,214,426"
10,2.253137216,48.91112189,11,"2,120,545"
11,-84.51188626,38.03708055,4,"322,600"
12,-87.95937097,43.03146501,5,"604,477"
13,-93.32778934,44.94513612,7,"368,380"
14,-46.54968154,-23.51900561,4,"17,962,000"
15,2.367702968,48.8369321,12,"2,158,732"
16,-71.06480015,42.34998438,17,"574,282"
17,126.9632178,37.55166639,2,"2,890,000"
18,12.53197094,55.65926482,16,"502,672"
19,12.53615059,55.69788659,2,"536,743"
20,151.1965143,-33.8845652,3,"189,543"
21,-102.2601346,21.84015311,2,"1,215,094"
22,2.125247295,41.36614561,1,"1,610,427"
'''), header=None)

In [73]:
data.columns = data.iloc[0]
data = data[1:]

In [127]:
data['Climate'] = None

In [75]:
data = data.reset_index(drop=True)

In [76]:
data.drop(columns=['xmin', 'ymin'], inplace=True)

In [77]:
data['LSI'] = None
data['Length'] = None

## Get LSI + Length data

In [82]:
for id in data['ID']:
    url = "https://raw.githubusercontent.com/thomaslu678/Praxis-Lab-25-26/refs/heads/main/assets/QGIS%20Outputs/" + str(id) + "/metadata.json"

    metadata_df = pd.read_json(url)

    area = metadata_df['total_area']['xmin']
    perimeter = metadata_df['total_perimeter']['xmin']
    length = metadata_df['centerline_length']['xmin']

    lsi = 0.25 * (perimeter / (np.sqrt(area)))

    data.at[int(id), 'LSI'] = lsi
    data.at[int(id), 'Length'] = length

In [90]:
data = data.drop(0)
data = data.drop(2)

In [91]:
data

0   ID Duration  Pop. Start Climate       LSI       Length
1    1        3     483,450    None  4.696409  3515.743123
3    3        2   2,718,782    None  3.441923  4602.754089
4    4        1   8,918,653    None  6.946714  4675.064944
5    5        3   8,920,000    None  2.202718   2325.39275
6    6        6     200,546    None  7.218315  8678.708547
7    7        9   2,660,000    None  3.873633  3552.180992
8    8        6   2,660,000    None  3.229026  1308.996598
9    9        8   8,214,426    None  6.712606  2500.390045
10  10       11   2,120,545    None  3.178745   951.480026
11  11        4     322,600    None  5.006901  3073.046719
12  12        5     604,477    None  2.580155  1257.084871
13  13        7     368,380    None  8.639568  9703.824187
14  14        4  17,962,000    None   3.28698  3689.026754
15  15       12   2,158,732    None    5.1338  3585.352396
16  16       17     574,282    None  3.476048  2565.886876
17  17        2   2,890,000    None  4.372659   1073.45146
18  18       16     502,672    None  4.938783  1949.955832
19  19        2     536,743    None  1.794161   524.750315
20  20        3     189,543    None  1.610999   284.724111
21  21        2   1,215,094    None  5.418939  6675.225094
22  22        1   1,610,427    None  2.195818   870.920145

# Get climate data

In [84]:
climate_url = "https://raw.githubusercontent.com/thomaslu678/Praxis-Lab-25-26/refs/heads/main/met/similarity_results.csv"

In [85]:
climate_df = pd.read_csv(climate_url)

In [92]:
climate_df.columns

Index(['ID', 'TMP_mean', 'TMP_std', 'DEW_mean', 'DEW_std', 'AA_mean', 'AA_std',
       'SLP_mean', 'SLP_std'],
      dtype='object')

In [87]:
average_climate_weights

array([0.25112125, 0.46151635, 0.22677015, 0.06059225])

In [88]:
climate_weights = np.repeat(average_climate_weights, 2) / 2

In [89]:
climate_weights

array([0.12556063, 0.12556063, 0.23075817, 0.23075817, 0.11338508,
       0.11338508, 0.03029612, 0.03029612])

In [117]:
import numpy as np

feature_cols = [
    'TMP_mean', 'TMP_std',
    'DEW_mean', 'DEW_std',
    'AA_mean', 'AA_std',
    'SLP_mean', 'SLP_std'
]

# Make sure weights are a NumPy array
climate_weights = np.asarray(climate_weights, dtype=float)

assert len(climate_weights) == len(feature_cols)


# =========================================================
# 1. Z-score normalize each column independently
# =========================================================

for col in feature_cols:
    mean = climate_df[col].mean(skipna=True)
    std = climate_df[col].std(skipna=True)

    climate_df[col] = (climate_df[col] - mean) / std


# =========================================================
# 2. Get target row
# =========================================================

target = climate_df.loc[
    climate_df['ID'] == 6,
    feature_cols
].iloc[0].to_numpy(dtype=float)


# =========================================================
# 3. Calculate weighted Euclidean distance
# =========================================================

def weighted_euclidean(row):
    x = row.to_numpy(dtype=float)

    # True where BOTH the comparison row and target
    # have a value for that feature
    mask = ~np.isnan(x) & ~np.isnan(target)

    if not np.any(mask):
        return np.nan

    differences = x[mask] - target[mask]
    weights = climate_weights[mask]

    # Weighted mean squared difference
    weighted_mse = np.sum(weights * differences**2) / np.sum(weights)

    return np.sqrt(weighted_mse)


# =========================================================
# 4. Calculate NON-weighted Euclidean distance
# =========================================================

def euclidean(row):
    x = row.to_numpy(dtype=float)

    # Same missing-data treatment
    mask = ~np.isnan(x) & ~np.isnan(target)

    if not np.any(mask):
        return np.nan

    differences = x[mask] - target[mask]

    return np.sqrt(np.sum(differences**2))


# =========================================================
# 5. Add distances to dataframe
# =========================================================

climate_df['weighted_distance'] = climate_df[feature_cols].apply(
    weighted_euclidean,
    axis=1
)

climate_df['euclidean_distance'] = climate_df[feature_cols].apply(
    euclidean,
    axis=1
)


# =========================================================
# 6. Convert weighted distance to similarity
# =========================================================

climate_df['similarity'] = (
    1 / (1 + climate_df['weighted_distance'])
)

In [131]:
# Create matching ID keys
data['_ID_key'] = data['ID'].astype(str)

climate_df['_ID_key'] = climate_df['ID'].astype(int).astype(str)

# Map climate similarity onto data
data['Climate'] = data['_ID_key'].map(
    climate_df.set_index('_ID_key')['similarity']
)

# Remove temporary columns
data.drop(columns='_ID_key', inplace=True)
climate_df.drop(columns='_ID_key', inplace=True)

In [134]:
data = data[['Duration', 'LSI', 'Length', 'Pop. Start', 'Climate']]

In [138]:
data['ID'] = data.index

In [141]:
data = data[['ID', 'Duration', 'LSI', 'Length', 'Pop. Start', 'Climate']]

In [144]:
type(data.iloc[0]['ID'])

numpy.int64

In [133]:
average_case_weights

array([0.03657074, 0.24262662, 0.27538361, 0.08275766, 0.36266136])

In [146]:
# Features and their order
feature_cols = [
    'Duration',
    'LSI',
    'Length',
    'Pop. Start',
    'Climate'
]

# Make sure weights are a NumPy array
average_case_weights = np.asarray(
    average_case_weights,
    dtype=float
)

assert len(average_case_weights) == len(feature_cols)

In [149]:
data['Pop. Start'] = data['Pop. Start'].str.replace(',', '').astype(int)

In [154]:
data['Duration'] = data['Duration'].astype(int)

In [155]:
data

0   ID  Duration       LSI       Length  Pop. Start   Climate
1    1         3  4.696409  3515.743123      483450  0.367333
3    3         2  3.441923  4602.754089     2718782  0.467331
4    4         1  6.946714  4675.064944     8918653  0.370631
5    5         3  2.202718   2325.39275     8920000  0.362485
6    6         6  7.218315  8678.708547      200546  1.000000
7    7         9  3.873633  3552.180992     2660000  0.415416
8    8         6  3.229026  1308.996598     2660000  0.413032
9    9         8  6.712606  2500.390045     8214426  0.439766
10  10        11  3.178745   951.480026     2120545  0.480289
11  11         4  5.006901  3073.046719      322600  0.408895
12  12         5  2.580155  1257.084871      604477  0.489610
13  13         7  8.639568  9703.824187      368380  0.455860
14  14         4   3.28698  3689.026754    17962000  0.257050
15  15        12    5.1338  3585.352396     2158732  0.458337
16  16        17  3.476048  2565.886876      574282  0.480208
17  17         2  4.372659   1073.45146     2890000  0.423758
18  18        16  4.938783  1949.955832      502672  0.459757
19  19         2  1.794161   524.750315      536743  0.433877
20  20         3  1.610999   284.724111      189543  0.293674
21  21         2  5.418939  6675.225094     1215094  0.374343
22  22         1  2.195818   870.920145     1610427  0.365574

In [156]:
# =========================================================
# 1. Normalize each feature independently
#    Z-score normalization, ignoring NaNs
# =========================================================

for col in feature_cols:
    mean = data[col].mean(skipna=True)
    std = data[col].std(skipna=True)

    data[col] = (data[col] - mean) / std

In [157]:
# =========================================================
# 2. Get target row (ID = 6)
# =========================================================

target = data.loc[
    data['ID'] == 6,
    feature_cols
].iloc[0].to_numpy(dtype=float)

In [158]:
target

array([ 0.0201721 ,  1.53080754,  2.1426418 , -0.66640307,  3.94565356])

In [160]:

# =========================================================
# 3. Weighted Euclidean distance
# =========================================================

def weighted_euclidean(row):
    x = row.to_numpy(dtype=float)

    # Only use features available in BOTH rows
    mask = ~np.isnan(x) & ~np.isnan(target)

    if not np.any(mask):
        return np.nan

    differences = x[mask] - target[mask]
    weights = average_case_weights[mask]

    # Weighted mean squared difference
    weighted_mse = (
        np.sum(weights * differences**2)
        / np.sum(weights)
    )

    return np.sqrt(weighted_mse)


# =========================================================
# 4. Calculate distance
# =========================================================

data['weighted_distance'] = data[feature_cols].apply(
    weighted_euclidean,
    axis=1
)


# =========================================================
# 5. Convert distance to similarity
# =========================================================

data['similarity'] = (
    1 / (1 + data['weighted_distance'])
)

In [161]:
data

,ID,Duration,LSI,Length,Pop. Start,Climate,weighted_distance,similarity
1,1,-0.615249,0.215345,0.120601,-0.602153,-0.503381,2.956246,0.252765
3,3,-0.827056,-0.439013,0.546321,-0.094488,0.199821,2.604822,0.277406
4,4,-1.038863,1.389137,0.574642,1.313562,-0.480189,2.855035,0.259401
5,5,-0.615249,-1.085401,-0.345592,1.313868,-0.537475,3.315702,0.231712
6,6,0.020172,1.530808,2.142642,-0.666403,3.945654,0.000000,1.000000
7,7,0.655593,-0.213827,0.134872,-0.107838,-0.165252,2.831608,0.260987
8,8,0.020172,-0.550064,-0.743657,-0.107838,-0.182015,3.090217,0.244486
9,9,0.443786,1.267022,-0.277055,1.153626,0.005983,2.745688,0.266974
10,10,1.079207,-0.576291,-0.883676,-0.230353,0.290945,2.915499,0.255395
11,11,-0.403442,0.377302,-0.052778,-0.638683,-0.211112,2.814798,0.262137
12,12,-0.191635,-0.888524,-0.763988,-0.574666,0.356490,2.901876,0.256287
13,13,0.231979,2.272154,2.544121,-0.628286,0.119160,2.342990,0.299133
14,14,-0.403442,-0.519834,0.188466,3.367393,-1.278912,3.650247,0.215042
15,15,1.291014,0.443494,0.147863,-0.221680,0.136576,2.592286,0.278374
16,16,2.350049,-0.421214,-0.251404,-0.581524,0.290374,2.747273,0.266861
17,17,-0.827056,0.046472,-0.835906,-0.055602,-0.106592,2.998329,0.250104
18,18,2.138242,0.341771,-0.492629,-0.597787,0.146558,2.766634,0.265489
19,19,-0.827056,-1.29851,-1.050801,-0.590050,-0.035430,3.244254,0.235613
20,20,-0.615249,-1.39405,-1.144806,-0.668902,-1.021365,3.743509,0.210814
21,21,-0.827056,0.592227,1.357991,-0.435990,-0.454089,2.726579,0.268343
22,22,-1.038863,-1.089,-0.915226,-0.346206,-0.515749,3.392372,0.227667

In [162]:
data.to_csv('output.csv', columns=['ID', 'similarity'], index=False)